onlyBuiltDependencies:
  - '@firebase/util'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - core-js
  - esbuild
  - prisma
  - protobufjs
  - sharp

overrides:
  body-parser@>=2.2.0 <2.2.1: '>=2.2.1'
  cookie@<0.7.0: '>=0.7.0'
  esbuild@<=0.24.2: '>=0.25.0'
  jws@<3.2.3: '>=3.2.3'
  jws@=4.0.0: '>=4.0.1'
  loader-utils@<1.4.1: '>=1.4.1'
  loader-utils@>=1.0.0 <1.4.2: '>=1.4.2'
  lodash@<2.1.0: ^2.1.0
  node-fetch@<2.6.7: '>=2.6.7'
  node-fetch@>=2.0.0 <2.6.1: '>=2.6.1'
  node-forge@<1.3.2: '>=1.3.2'
  on-headers@<1.1.0: '>=1.1.0'
  path-to-regexp@>=2.0.0 <3.3.0: '>=3.3.0'
  send@<0.19.0: '>=0.19.0'
