import type { MetadataRoute } from "next";

/**
 * Robots.ts - Dynamic robots configuration for Luxela
 * Generated by Next.js to guide search engine crawlers
 * 
 * Complements /public/robots.txt with advanced features
 */
export default function robots(): MetadataRoute.Robots {
  const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://theluxela.com";

  return {
    // Main crawling rules
    rules: [
      // Default rule for all bots
      {
        userAgent: "*",
        allow: "/",
        disallow: [
          "/admin/",
          "/api/",
          "/_trpc/",
          "/account/",
          "/*.json$",
          "/verify-email",
          "/reset-password",
          "/forgot-password",
          "/select-role",
        ],
        crawlDelay: 1,
      },
      // Google - No crawl delay (trusted)
      {
        userAgent: "Googlebot",
        allow: "/",
        disallow: [
          "/admin/",
          "/api/",
          "/_trpc/",
          "/account/",
          "/*.json$",
          "/verify-email",
          "/reset-password",
          "/forgot-password",
          "/select-role",
        ],
        crawlDelay: 0,
      },
      // Bing - Standard crawl delay
      {
        userAgent: "Bingbot",
        allow: "/",
        disallow: [
          "/admin/",
          "/api/",
          "/_trpc/",
          "/account/",
          "/*.json$",
          "/verify-email",
          "/reset-password",
          "/forgot-password",
          "/select-role",
        ],
        crawlDelay: 1,
      },
      // DuckDuckGo
      {
        userAgent: "DuckDuckBot",
        allow: "/",
        crawlDelay: 1,
      },
      // Block aggressive crawlers
      {
        userAgent: ["AhrefsBot", "SemrushBot", "MJ12bot", "SentiBot"],
        disallow: "/",
      },
    ],

    // Multiple sitemaps for comprehensive coverage
    sitemap: [
      `${SITE_URL}/sitemap.xml`, // Static XML sitemap
      `${SITE_URL}/sitemap.ts`, // Dynamic sitemap
    ],

    // Host preference (helps with canonicalization)
    host: SITE_URL,

    // Tell search engines about your site
    // Useful for migration or subdomain consolidation
    // Example: "https://www.theluxela.com"
  };
}