// Dummy data for the dashboard
export const dashboardData = {
    stats: {
      totalRevenue: {
        value: "₦4,400,000",
        change: "8.4%",
        changeType: "positive" as const,
        subtext: "₦800,000 today",
      },
      totalSales: {
        value: "₦2,400,000",
        change: "13.4%",
        changeType: "positive" as const,
        subtext: "₦200,000 today",
      },
      totalOrders: {
        value: "1,230",
        change: "3%",
        changeType: "positive" as const,
        subtext: "200 today",
      },
      refunded: {
        value: "2",
        change: "1%",
        changeType: "negative" as const,
        subtext: "2 today",
      },
    },
    revenueReport: [
      { month: "Jan", income: 30000 },
      { month: "Feb", income: 35000 },
      { month: "Mar", income: 45000 },
      { month: "Apr", income: 90000 },
      { month: "May", income: 70000 },
      { month: "Jun", income: 40000 },
      { month: "Jul", income: 110000 },
      { month: "Aug", income: 60000 },
      { month: "Sep", income: 100000 },
      { month: "Oct", income: 105000 },
      { month: "Nov", income: 110000 },
      { month: "Dec", income: 70000 },
    ],
    visitorTraffic: [
      { source: "Homepage Results", percentage: 30 },
      { source: "Category Browsing", percentage: 40 },
      { source: "Search Results", percentage: 20 },
      { source: "Shares", percentage: 10 },
    ],
    topSellingProducts: [
      {
        id: 1,
        name: "Baz vest",
        category: "Men Clothing",
        price: "₦40,000.00",
        quantitySold: 300,
        status: "In stock",
      },
      {
        id: 2,
        name: "Rose dress",
        category: "Women Clothing",
        price: "₦50,000.00",
        quantitySold: 280,
        status: "Low stock",
      },
      {
        id: 3,
        name: "Product Name",
        category: "Category",
        price: "Price",
        quantitySold: 30,
        status: "Sold out",
      },
    ],
  }
  
  // Dummy data for sales
  export const salesData = [
    {
      id: "22739",
      product: "Nike Elite Crew Socks",
      customer: "Jane Cooper",
      orderDate: "22 Oct, 2025",
      paymentMethod: "Local Currency",
      amount: "NGN135,000",
      payoutStatus: "In escrow",
      deliveryStatus: "Not Shipped",
    },
    {
      id: "97174",
      product: "Acrylic sweater",
      customer: "Wade Warren",
      orderDate: "8 Sep, 2025",
      paymentMethod: "Stable Coin",
      amount: "NGN51,000",
      payoutStatus: "Processing",
      deliveryStatus: "Not Shipped",
    },
    {
      id: "43756",
      product: "Cable sweater",
      customer: "Esther Howard",
      orderDate: "24 May, 2025",
      paymentMethod: "Stable Coin",
      amount: "20.59 USDT",
      payoutStatus: "Paid",
      deliveryStatus: "Delivered",
    },
    {
      id: "43178",
      product: "Fanny sweater",
      customer: "Albert Flores",
      orderDate: "17 Oct, 2025",
      paymentMethod: "Stable Coin",
      amount: "74.13 USDT",
      payoutStatus: "Processing",
      deliveryStatus: "Not Shipped",
    },
    {
      id: "43756",
      product: "Turtle neck sweater",
      customer: "Floyd Miles",
      orderDate: "21 Sep, 2025",
      paymentMethod: "Local Currency",
      amount: "NGN40,000",
      payoutStatus: "In escrow",
      deliveryStatus: "Not Shipped",
    },
    {
      id: "39635",
      product: "Grandpa sweater",
      customer: "Devon Lane",
      orderDate: "22 Oct, 2025",
      paymentMethod: "Stable Coin",
      amount: "23 USDT",
      payoutStatus: "Paid",
      deliveryStatus: "In transit",
    },
    {
      id: "22739",
      product: "Shawl collar sweater",
      customer: "Jenny Wilson",
      orderDate: "1 Feb, 2025",
      paymentMethod: "Local Currency",
      amount: "NGN51,000",
      payoutStatus: "In escrow",
      deliveryStatus: "Not Shipped",
    },
    {
      id: "43178",
      product: "Washed Jersey T-shirt",
      customer: "Guy Hawkins",
      orderDate: "22 Oct, 2025",
      paymentMethod: "Local Currency",
      amount: "NGN45,000",
      payoutStatus: "Paid",
      deliveryStatus: "Delivered",
    },
    {
      id: "39635",
      product: "Donegal Sweater",
      customer: "Robert Fox",
      orderDate: "8 Sep, 2025",
      paymentMethod: "Local Currency",
      amount: "NGN55,000",
      payoutStatus: "Paid",
      deliveryStatus: "Delivered",
    },
    {
      id: "39635",
      product: "Mauve Rose",
      customer: "Jerome Bell",
      orderDate: "22 Oct, 2025",
      paymentMethod: "Local Currency",
      amount: "NGN51,000",
      payoutStatus: "Processing",
      deliveryStatus: "Not Shipped",
    },
    {
      id: "39635",
      product: "V-neck sweater",
      customer: "Bessie Cooper",
      orderDate: "1 Feb, 2025",
      paymentMethod: "Stable Coin",
      amount: "43 USDT",
      payoutStatus: "Paid",
      deliveryStatus: "Delivered",
    },
    {
      id: "43178",
      product: "Acrylic sweater",
      customer: "Cody Fisher",
      orderDate: "1 Feb, 2025",
      paymentMethod: "Stable Coin",
      amount: "24 USDT",
      payoutStatus: "Paid",
      deliveryStatus: "Delivered",
    },
    {
      id: "43756",
      product: "Tennis sweater",
      customer: "Jacob Jones",
      orderDate: "1 Feb, 2025",
      paymentMethod: "Stable Coin",
      amount: "17.42 USDT",
      payoutStatus: "In escrow",
      deliveryStatus: "Not Shipped",
    },
  ]
  
  // Dummy data for notifications
  export const notificationsData = [
    {
      id: 1,
      message: "You've received a new order. Time to prepare for delivery!",
      time: "Just now",
      read: false,
      starred: false,
    },
    {
      id: 2,
      message: "You've received a 5 star review from a happy customer",
      time: "30 mins ago",
      read: false,
      starred: false,
    },
    {
      id: 3,
      message: "You've edited a listing, changes are live",
      time: "10:30am",
      read: true,
      starred: false,
    },
    {
      id: 4,
      message: "You've received feedback on your last orders",
      time: "12:30pm",
      read: true,
      starred: false,
    },
    {
      id: 5,
      message: "Reminder: Follow up a recent order to ask for a review",
      time: "12:30pm",
      read: true,
      starred: false,
    },
    {
      id: 6,
      message: "Reminder: Follow up a recent order to ask for a review",
      time: "12:30pm",
      read: true,
      starred: false,
    },
    {
      id: 7,
      message: "Reminder: Follow up a recent order to ask for a review",
      time: "12:30pm",
      read: true,
      starred: false,
    },
    {
      id: 8,
      message: "Reminder: Follow up a recent order to ask for a review",
      time: "12:30pm",
      read: true,
      starred: false,
    },
    {
      id: 9,
      message: "Reminder: Follow up a recent order to ask for a review",
      time: "12:30pm",
      read: true,
      starred: false,
    },
    {
      id: 10,
      message: "Reminder: Follow up a recent order to ask for a review",
      time: "12:30pm",
      read: true,
      starred: false,
    },
    {
      id: 11,
      message: "Reminder: Follow up a recent order to ask for a review",
      time: "12:30pm",
      read: true,
      starred: false,
    },
  ]
  
  // Order detail for the selected order
  export const orderDetail = {
    id: "97174",
    customer: "Wade Warren",
    product: "Acrylic sweater",
    quantity: "2 Item",
    orderDate: "8 Sep, 2025",
    amount: "₦102,000",
    paymentMethod: "Local Currency",
    paymentStatus: "In Escrow",
    shippingAddress: "23 Market Street, Ilorin, Nigeria",
    estimatedDelivery: "May 4, 2025 - May 12, 2025",
    status: "Not Shipped",
  }
  